"""Transparency labels shown to readers.

Three variants keyed off attribution. The confidence percentage is injected so
the same variant still communicates *how sure* the system is. Written for a
non-technical reader: plain language, no jargon, and explicit about uncertainty
plus the creator's right to appeal.
"""


def build_label(result):
    attribution = result["attribution"]
    pct = round(result["confidence"] * 100)

    if attribution == "likely_ai":
        title = "🤖 Likely AI-generated"
        body = (
            f"Our analysis suggests this content was probably created with the help of "
            f"AI ({pct}% confidence). This is an automated estimate, not a certainty — "
            f"AI detection is imperfect. If you wrote this yourself, you can appeal."
        )
    elif attribution == "likely_human":
        title = "✍️ Likely human-written"
        body = (
            f"Our analysis suggests this content was probably written by a person "
            f"({pct}% confidence). This is an automated estimate and is not a guarantee."
        )
    else:  # uncertain
        title = "❓ Uncertain origin"
        body = (
            f"We couldn't confidently determine whether this content was written by a "
            f"person or generated by AI (only {pct}% certainty either way). We're showing "
            f"this honestly rather than guessing. Treat the origin as unknown."
        )

    return {
        "title": title,
        "body": body,
        "text": f"{title} — {body}",
        "attribution": attribution,
        "confidence_pct": pct,
    }
