"""Two independent detection signals.

Signal 1 (semantic)  : Groq LLM holistic assessment -> P(AI) in [0,1].
Signal 2 (structural): stylometric heuristics       -> P(AI) in [0,1].

The signals are deliberately independent: one reads meaning/coherence, the
other measures surface statistics. They can disagree, and that disagreement is
what makes the combined score informative (see scoring.py).
"""
import json
import math
import os
import re
import statistics

# ---------------------------------------------------------------------------
# Signal 1: LLM semantic classifier (Groq)
# ---------------------------------------------------------------------------

_LLM_PROMPT = (
    "You are a forensic text analyst. Assess whether the TEXT was written by a "
    "human or generated by an AI language model. Judge holistically: semantic "
    "coherence, originality of phrasing, idiosyncrasy, and 'voice'. AI text is "
    "often fluent but generic, evenly hedged, and lacking lived specifics.\n"
    "Respond with ONLY a JSON object: "
    '{\"p_ai\": <float 0..1>, \"rationale\": <short string>} '
    "where p_ai is the probability the text is AI-generated.\n\nTEXT:\n"
)


def llm_signal(text):
    """Return {'available': bool, 'score': float|None, 'rationale': str}.

    score = P(AI). If GROQ_API_KEY is absent or the call fails, returns
    available=False so the scorer can fall back to stylometry alone.
    """
    key = os.environ.get("GROQ_API_KEY")
    if not key:
        return {"available": False, "score": None, "rationale": "GROQ_API_KEY not set"}
    try:
        from groq import Groq
        client = Groq(api_key=key)
        resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": _LLM_PROMPT + text}],
            temperature=0,
            max_tokens=200,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        score = float(data.get("p_ai"))
        score = max(0.0, min(1.0, score))
        return {"available": True, "score": score, "rationale": str(data.get("rationale", ""))[:300]}
    except Exception as e:  # network/parse/quota -> degrade gracefully
        return {"available": False, "score": None, "rationale": f"llm_error: {e}"}


# ---------------------------------------------------------------------------
# Signal 2: stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

_WORD_RE = re.compile(r"[A-Za-z']+")
_SENT_RE = re.compile(r"[.!?]+")
_CASUAL_RE = re.compile(r"(\bi\b|\bok\b|\bgonna\b|\bwanna\b|\bkinda\b|\bhonestly\b|\byeah\b|\blol\b|\bidk\b)")


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def stylo_signal(text):
    """Structural P(AI) from three interpretable metrics + a casual discount.

    Metrics:
      burstiness  - coefficient of variation of sentence length.
                    Human prose varies (high CV); AI prose is uniform (low CV).
      ttr         - type-token ratio (vocabulary diversity). Mid-range TTR is
                    AI-typical; very low (repetitive/poetic) or very high
                    (terse/casual) skews human.
      punct       - density of expressive punctuation (! ? ... --). Sparse,
                    even punctuation reads AI; bursty punctuation reads human.
    A casual-marker discount pulls the score toward human for slang/lowercase-i.
    """
    words = _WORD_RE.findall(text.lower())
    n_words = len(words)
    sentences = [s for s in _SENT_RE.split(text) if s.strip()]
    sent_lengths = [len(_WORD_RE.findall(s)) for s in sentences] or [n_words]

    # 1. burstiness -> AI-likeness
    mean_len = statistics.mean(sent_lengths) if sent_lengths else 0
    sd_len = statistics.pstdev(sent_lengths) if len(sent_lengths) > 1 else 0
    cv = (sd_len / mean_len) if mean_len else 0
    burstiness_ai = _clamp(1 - cv / 0.65)  # cv>=0.65 (very human) -> 0

    # 2. type-token ratio -> AI-likeness (gaussian centered at 0.5)
    window = words[:200]
    ttr = (len(set(window)) / len(window)) if window else 0.5
    ttr_ai = math.exp(-((ttr - 0.5) ** 2) / (2 * 0.15 ** 2))

    # 3. expressive punctuation density -> human-likeness
    expressive = len(re.findall(r"[!?]|\.\.\.|--|—", text))
    punct_density = expressive / max(n_words, 1)
    punct_ai = _clamp(1 - punct_density * 12)

    p_ai = 0.55 * burstiness_ai + 0.25 * ttr_ai + 0.20 * punct_ai

    # casual-marker discount (protects informal human writers from false AI flags)
    casual = len(_CASUAL_RE.findall(text.lower()))
    casual_discount = min(casual / max(n_words, 1) * 8, 0.40)
    p_ai = _clamp(p_ai - casual_discount)

    return {
        "score": round(p_ai, 4),
        "metrics": {
            "sentence_length_cv": round(cv, 4),
            "type_token_ratio": round(ttr, 4),
            "expressive_punct_density": round(punct_density, 4),
            "casual_markers": casual,
            "n_words": n_words,
            "n_sentences": len(sentences),
        },
    }
