"""Two independent detection signals.

Signal 1 (semantic)  : Groq LLM holistic assessment -> P(AI) in [0,1].
Signal 2 (structural): stylometric heuristics       -> P(AI) in [0,1].

The signals are deliberately independent: one reads meaning/coherence, the
other measures surface statistics. They can disagree, and that disagreement is
what makes the combined score informative (see scoring.py).
"""
import json
import math
import os
import re
import statistics

# ---------------------------------------------------------------------------
# Signal 1: LLM semantic classifier (Groq)
# ---------------------------------------------------------------------------

_LLM_PROMPT = (
    "You are a forensic text analyst. Assess whether the TEXT was written by a "
    "human or generated by an AI language model. Judge holistically: semantic "
    "coherence, originality of phrasing, idiosyncrasy, and 'voice'. AI text is "
    "often fluent but generic, evenly hedged, and lacking lived specifics.\n"
    "Respond with ONLY a JSON object: "
    '{\"p_ai\": <float 0..1>, \"rationale\": <short string>} '
    "where p_ai is the probability the text is AI-generated.\n\nTEXT:\n"
)


def llm_signal(text):
    """Return {'available': bool, 'score': float|None, 'rationale': str}.

    score = P(AI). If GROQ_API_KEY is absent or the call fails, returns
    available=False so the scorer can fall back to stylometry alone.
    """
    key = os.environ.get("GROQ_API_KEY")
    if not key:
        return {"available": False, "score": None, "rationale": "GROQ_API_KEY not set"}
    try:
        from groq import Groq
        client = Groq(api_key=key)
        resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": _LLM_PROMPT + text}],
            temperature=0,
            max_tokens=200,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        score = float(data.get("p_ai"))
        score = max(0.0, min(1.0, score))
        return {"available": True, "score": score, "rationale": str(data.get("rationale", ""))[:300]}
    except Exception as e:  # network/parse/quota -> degrade gracefully
        return {"available": False, "score": None, "rationale": f"llm_error: {e}"}


# ---------------------------------------------------------------------------
# Signal 2: stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

_WORD_RE = re.compile(r"[A-Za-z']+")
_SENT_RE = re.compile(r"[.!?]+")
_CASUAL_RE = re.compile(r"(\bi\b|\bok\b|\bgonna\b|\bwanna\b|\bkinda\b|\bhonestly\b|\byeah\b|\blol\b|\bidk\b)")


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def stylo_signal(text):
    """Structural P(AI) from three interpretable metrics + a casual discount.

    Metrics:
      burstiness  - coefficient of variation of sentence length.
                    Human prose varies (high CV); AI prose is uniform (low CV).
      ttr         - type-token ratio (vocabulary diversity). Mid-range TTR is
                    AI-typical; very low (repetitive/poetic) or very high
                    (terse/casual) skews human.
      punct       - density of expressive punctuation (! ? ... --). Sparse,
                    even punctuation reads AI; bursty punctuation reads human.
    A casual-marker discount pulls the score toward human for slang/lowercase-i.
    """
    words = _WORD_RE.findall(text.lower())
    n_words = len(words)
    sentences = [s for s in _SENT_RE.split(text) if s.strip()]
    sent_lengths = [len(_WORD_RE.findall(s)) for s in sentences] or [n_words]

    # 1. burstiness -> AI-likeness
    mean_len = statistics.mean(sent_lengths) if sent_lengths else 0
    sd_len = statistics.pstdev(sent_lengths) if len(sent_lengths) > 1 else 0
    cv = (sd_len / mean_len) if mean_len else 0
    burstiness_ai = _clamp(1 - cv / 0.65)  # cv>=0.65 (very human) -> 0

    # 2. type-token ratio -> AI-likeness (gaussian centered at 0.5)
    window = words[:200]
    ttr = (len(set(window)) / len(window)) if window else 0.5
    ttr_ai = math.exp(-((ttr - 0.5) ** 2) / (2 * 0.15 ** 2))

    # 3. expressive punctuation density -> human-likeness
    expressive = len(re.findall(r"[!?]|\.\.\.|--|—", text))
    punct_density = expressive / max(n_words, 1)
    punct_ai = _clamp(1 - punct_density * 12)

    p_ai = 0.55 * burstiness_ai + 0.25 * ttr_ai + 0.20 * punct_ai

    # casual-marker discount (protects informal human writers from false AI flags)
    casual = len(_CASUAL_RE.findall(text.lower()))
    casual_discount = min(casual / max(n_words, 1) * 8, 0.40)
    p_ai = _clamp(p_ai - casual_discount)

    return {
        "score": round(p_ai, 4),
        "metrics": {
            "sentence_length_cv": round(cv, 4),
            "type_token_ratio": round(ttr, 4),
            "expressive_punct_density": round(punct_density, 4),
            "casual_markers": casual,
            "n_words": n_words,
            "n_sentences": len(sentences),
        },
    }


# ---------------------------------------------------------------------------
# Signal 3: input provenance (behavioral) — optional, browser-captured
# ---------------------------------------------------------------------------

def behavior_signal(behavior):
    """P(AI) from *how the text entered the box*, not its content.

    Only the web UI can supply this (curl can't), so it is optional. Input is a
    dict the front-end builds while the creator works:
        final_len, typed_chars, pasted_chars, paste_count,
        max_paste_len, keystrokes, backspaces, duration_ms

    Reasoning — and its deliberate limits:
      * Typed live, over time, with corrections  -> strong human provenance.
      * Pasted as a finished block               -> WEAK provenance, NOT proof
        of AI (people paste their own drafts). So a paste only nudges suspicion
        upward; it can never, alone, force an "AI" verdict. The score is clamped
        to [0.10, 0.65] for exactly this reason.
    """
    if not behavior or not isinstance(behavior, dict):
        return {"available": False, "score": None}

    final_len = max(int(behavior.get("final_len", 0)), 0)
    if final_len < 1:
        return {"available": False, "score": None}

    typed = max(int(behavior.get("typed_chars", 0)), 0)
    pasted = max(int(behavior.get("pasted_chars", 0)), 0)
    paste_count = int(behavior.get("paste_count", 0))
    max_paste = int(behavior.get("max_paste_len", 0))
    keystrokes = int(behavior.get("keystrokes", 0))
    backspaces = int(behavior.get("backspaces", 0))
    duration_ms = int(behavior.get("duration_ms", 0))

    typed_ratio = _clamp(typed / final_len)

    # base: all-typed -> 0.15 (human), all-pasted -> 0.55 (weak provenance)
    score = 0.55 - 0.40 * typed_ratio

    # a single dominant paste of the whole text -> weaker provenance
    if final_len and max_paste / final_len > 0.7:
        score += 0.08
    # organic editing (real corrections while typing) -> more human
    if backspaces > 3 and typed_ratio > 0.5:
        score -= 0.05
    # plausible human typing cadence present -> more human
    if keystrokes > 20 and duration_ms > 3000 and typed_ratio > 0.5:
        score -= 0.05

    score = round(_clamp(score, 0.10, 0.65), 4)

    if typed_ratio >= 0.8:
        verdict = "typed_live"        # strong human provenance
    elif typed_ratio <= 0.3:
        verdict = "pasted_block"      # weak provenance
    else:
        verdict = "mixed"

    return {
        "available": True,
        "score": score,
        "verdict": verdict,
        "metrics": {
            "typed_ratio": round(typed_ratio, 3),
            "paste_count": paste_count,
            "max_paste_len": max_paste,
            "keystrokes": keystrokes,
            "backspaces": backspaces,
            "duration_ms": duration_ms,
        },
    }


# ---------------------------------------------------------------------------
# Multi-modal: image-metadata signal (second content type)
# ---------------------------------------------------------------------------

# Markers AI image generators leave in EXIF/XMP/C2PA "software" or provenance.
_AI_TOOL_MARKERS = (
    "dall-e", "dalle", "midjourney", "niji", "stable diffusion", "sdxl", "sd ",
    "comfyui", "automatic1111", "firefly", "adobe firefly", "leonardo", "ideogram",
    "flux", "dreamstudio", "gpt-4o", "gemini", "imagen", "runway", "ai generated",
)


def metadata_signal(meta):
    """P(AI) for an IMAGE based on its metadata, not pixels.

    `meta` is a dict the caller extracts from the file's EXIF/XMP/C2PA, e.g.
        {software, camera_make, camera_model, has_exif, c2pa}

    Reasoning:
      * A known AI generator named in software/C2PA  -> strong AI evidence.
      * A real camera make/model + intact EXIF        -> strong human-capture.
      * Stripped metadata (no EXIF, no camera)        -> unknown; screenshots and
        re-exports also strip EXIF, so this is honestly uncertain.
    Limits: metadata is trivially editable — absence proves nothing, and a
    determined faker can forge a camera tag. Treated as one signal, not proof.
    """
    if not meta or not isinstance(meta, dict):
        return {"available": False, "score": None}

    software = str(meta.get("software", "")).lower()
    c2pa = str(meta.get("c2pa", "")).lower()
    make = str(meta.get("camera_make", "")).strip()
    model = str(meta.get("camera_model", "")).strip()
    has_exif = bool(meta.get("has_exif", bool(make or model)))

    blob = software + " " + c2pa
    if any(m in blob for m in _AI_TOOL_MARKERS):
        score, verdict = 0.92, "ai_tool_tagged"
    elif (make or model) and has_exif:
        score, verdict = 0.10, "camera_capture"
    elif not has_exif and not make and not model:
        score, verdict = 0.50, "metadata_stripped"
    else:
        score, verdict = 0.45, "inconclusive"

    return {
        "available": True,
        "score": score,
        "verdict": verdict,
        "metrics": {"software": software or None, "camera": (make + " " + model).strip() or None,
                    "has_exif": has_exif, "c2pa": c2pa or None},
    }
